name: Build & Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Package
        uses: actions/upload-pages-artifact@v2
        with:
          path: site/

  deploy:

    name: Deploy

    needs:
      - build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    if: |
      github.event_name == 'push' && github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
